name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

         script: |
           cd /root/fastapitest
           git pull origin main
           source venv/bin/activate
           pip install -r requirements.txt
           sudo systemctl restart fastapi
           sudo systemctl status fastapi --no-pager
           echo "=== Last 50 log lines ==="
           sudo journalctl -u fastapi -n 50 --no-pager
